/**
 * Extracts merge tags (`{{variable}}`) and URLs (`https://...`) from a string, 
 * replacing them with resilient numeric placeholders (e.g., `[[1]]`) that machine 
 * translation engines (like LibreTranslate) will protect and pass through untouched.
 * * @param text - The original text containing the variables and URLs to be protected.
 * @returns An object containing the translation-ready `scrubbed` string and a `map` 
 * to reference the original contents back to their assigned placeholder keys.
 * * @example
 * ```typescript
 * const { scrubbed, map } = extractPlaceholders("Hello {{name}}, visit [https://example.com](https://example.com)");
 * // scrubbed: "Hello [[1]], visit [[2]]"
 * ```
 */
export function extractPlaceholders(text: string): {
    scrubbed: string
    map: Map<string, string>
} {
    const PATTERN = /(\{\{(.+?)\}\})|(https?:\/\/[^\s<>"']+(?<![.,!?;:)\]}>]))/g
    const map = new Map<string, string>()
    let counter = 0
    
    const scrubbed = text.replace(PATTERN, (match) => {
        counter++
        const ph = `[[${counter}]]`
        
        map.set(ph, match)
        return ph
    })
    
    return { scrubbed, map }
}

/**
 * Restores the original merge tags and URLs into the translated text string.
 * Uses a flexible regular expression matching strategy to find placeholders even if 
 * the translation engine introduced formatting artifacts like unexpected spacing 
 * (e.g., converting `[[1]]` into `[[ 1 ]]` or `[ [1] ]`).
 * * @param text - The translated text string containing the numeric placeholders.
 * @param map - The placeholder-to-original-string map generated by {@link extractPlaceholders}.
 * @returns The final translated string with all original variables and URLs fully restored.
 * * @example
 * ```typescript
 * const translated = "Hola [[ 1 ]], visite [[2]]";
 * const finalResult = restorePlaceholders(translated, map);
 * // finalResult: "Hola {{name}}, visite [https://example.com](https://example.com)"
 * ```
 */
export function restorePlaceholders(
    text: string,
    map: Map<string, string>
): string {
    let restoredText = text
    for (const [ph, original] of map) {
        // Strip out any accidental spaces inside the brackets
        // e.g., if [[1]] accidentally became [ [1] ] or [[ 1 ]]
        const num = ph.replace(/[\[\]]/g, '')
        const flexibleRegex = new RegExp(`\\[\\s*\\[\\s*${num}\\s*\\]\\s*\\]`, 'g')
        
        restoredText = restoredText.replace(flexibleRegex, original)
    }
    return restoredText
}